################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
PP_SRCS := 
CC_SRCS := 
FSY_SRCS := 
P_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
P_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
CXX_DEPS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_ioport \
ra_gen \
src/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/BayesFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables \
src/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/InterpolationFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/QuaternionMathFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/BasicMathFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/ConcatenationFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/PoolingFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/ReshapeFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/SVDFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions \
src/edge-impulse-sdk/classifier \
src/edge-impulse-sdk/dsp/dct \
src/edge-impulse-sdk/dsp/image \
src/edge-impulse-sdk/dsp/kissfft \
src/edge-impulse-sdk/dsp \
src/edge-impulse-sdk/porting/arduino \
src/edge-impulse-sdk/porting/ecm3532 \
src/edge-impulse-sdk/porting/himax \
src/edge-impulse-sdk/porting/mbed \
src/edge-impulse-sdk/porting/mingw32 \
src/edge-impulse-sdk/porting/posix \
src/edge-impulse-sdk/porting/renesas-ra65 \
src/edge-impulse-sdk/porting/silabs \
src/edge-impulse-sdk/porting/sony \
src/edge-impulse-sdk/porting/stm32-cubeai \
src/edge-impulse-sdk/porting/ti \
src/edge-impulse-sdk/porting/zephyr \
src/edge-impulse-sdk/tensorflow/lite/c \
src/edge-impulse-sdk/tensorflow/lite/core/api \
src/edge-impulse-sdk/tensorflow/lite/kernels/internal \
src/edge-impulse-sdk/tensorflow/lite/kernels \
src/edge-impulse-sdk/tensorflow/lite/micro \
src/edge-impulse-sdk/tensorflow/lite/micro/kernels \
src/edge-impulse-sdk/tensorflow/lite/micro/memory_planner \
src \
src/tflite-model \

